### ISSUE TITLE
在gradle里面引用的问题

### ISSUE THREAD

**Issue by wu21731** [dalong982242260/LoopRotarySwitch#1]
在gradle里面引用的时候，orientation重复定义了，导致项目会build出错

**Comment by yixiaolunhui** [comment]
我一会看看，你可以先引modle下

**Comment by yixiaolunhui** [comment]
我测试没有问题啊，你引入的是    compile 'com.dalong:loopview:1.0.2'吗

**Comment by wu21731** [comment]
是引用的 compile 'com.dalong:loopview:1.0.2'，建议你把相关的一些参数名称稍微的加点前缀，便于跟其他的引用项目区分，我目前直接用moudle，修改了attr里面的名字，没有报错了

**Comment by yixiaolunhui** [comment]
知道了可能与你的重复了
