### ISSUE TITLE
为什么addview没反应

### ISSUE THREAD

**Issue by LuoGuoXin** [dalong982242260/LoopRotarySwitch#3]
for (int j = 0; j < petList.size(); j++) {
             View view = View.inflate(PetCountActivity.this, R.layout.item_pet, null);
            loopRotarySwitchView.addView(view);
        }

我用addview，也设置了点击事件和选择时间，发现只有一个view，而且不能旋转，点击也没反应，什么回事？

**Comment by yixiaolunhui** [comment]
可以呀我测试没问题，你可以加我qq982242260我试试

**Comment by yixiaolunhui** [comment]
loopRotarySwitchView有没有设置？加上这些试试 mLoopRotarySwitchView
                .setR(width/3)//设置R的大小
                .setAutoRotation(true)//是否自动切换
                .setAutoRotationTime(2000);//自动切换的时间  单位毫秒

**Comment by LuoGuoXin** [comment]
设置了，还是不行，然后我用你防QQ的那个库了

**Comment by yixiaolunhui** [comment]
啥东西？

**Comment by LCM-93** [comment]
我这也是这个情况，addView加入了4个ImageView，只有最后一个ImageView。

**Comment by LCM-93** [comment]
貌似在任何回调方法中调用addView之后都只会显示最后一个加入的View，感觉像是界面没有自动刷新，误打误撞找到解决方法，在addview之后 手动调用  loopRotarySwitchView.checkChildView()  方法就可以了，希望能提供一点解决BUG的思路。

**Comment by fghjhuang** [comment]
我的思路是把这个view放到linerlayout里面，然后要刷新数据的时候就删除这个view重新新建一个这个对象加入新的view进入
