### ISSUE TITLE
添加刷新图片遇到的bug

### ISSUE THREAD

**Issue by fengfutong** [dalong982242260/LoopRotarySwitch#4]
removeallviews之后，再重新添加，只有一张图片。不removeallviews，而是直接等两秒后，再重新添加，旋转图片后面有一张静止不动的图片。刚才不好意思，写到wiki里面去了

**Comment by yixiaolunhui** [comment]
你可以直接在xml布局中写个LinearLayout 然后动态添加LoopRotarySwitch 控件   每次刷新清理Linearlayout 然后从新添加/LoopRotarySwitch

**Comment by fengfutong** [comment]
你的方法解决了，谢谢
